
right_format = """
$cmd_duration
$time
"""

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

# [aws]
# format = 'on [$symbol($profile )(\($region\) )]($style)'
# style = "bold blue"

# [aws.region_aliases]
# ap-northeast-1 = "jp"

# [custom.arch]
# command = "uname -m"
# when = """ test $(uname -m) = "x86_64" """
# style = "bold yellow"
# format = "[$output]($style)"

[docker_context]
format = "via [🐋 $context](blue bold)"

[git_branch]
symbol = " "

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user🌱]($style) "
disabled = false
show_always = true

[hostname]
style = "bold purple"

[memory_usage]
disabled = false
threshold = 0
format = "[$symbol$ram( $percentage%)]($style) "

[time]
disabled = false
style = 'fg:#73daca'
format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%T'
utc_time_offset = '+9'

