[[snippets]]
  description = "yahoo-crawler ignore_sellers.txt をリモート更新"
  command = "scp /home/db97531/.ghq/bitbucket.org/db97531/yahoo-crawler/ignore_sellers.txt vps:/home/db97531/.ghq/bitbucket.org/db97531/yahoo-crawler/"
  output = ""

[[snippets]]
  description = "git管理している途中から.gitignoreを追加して、その設定を反映させる"
  command = "git rm -r --cached ."
  output = ""

[[snippets]]
  description = "全てのコンテナを強制的に削除する"
  command = "docker rm -f $(docker ps -a -q)"
  output = ""

[[snippets]]
  description = "GoでWindows用コンパイル"
  command = "CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -o XXX.exe xxx.go"
  output = ""

[[snippets]]
  description = "GoでWindows用コンパイル(x86)"
  command = "CGO_ENABLED=1 CC=i686-w64-mingw32-gcc GOOS=windows GOARCH=386 go build -o XXXX.exe main.go"
  output = ""

[[snippets]]
  description = "後から.gitignoreを反映させたい時"
  command = "git rm -r --cached ."
  output = ""

[[snippets]]
  description = "フォントサイズを20に"
  command = "urxvt-font 20"
  output = ""

[[snippets]]
  description = "フォントサイズを14に"
  command = "urxvt-font 14"
  output = ""

[[snippets]]
  description = "ヤフオククローラstatus確認"
  command = "ssh vps systemctl status yahoo"
  output = ""

[[snippets]]
  description = "VPSヤフオククローラーDB編集"
  command = "ssh -X vps sqlitebrowser ~/.ghq/bitbucket.org/db97531/yahoo-crawler/db/db.sqlite"
  output = ""

[[snippets]]
  description = "リモートブランチをローカルに持ってくる"
  command = "git checkout -b new-branch origin/new-branch"
  output = ""

[[snippets]]
  description = "VM共有ディレクトリ有効化"
  command = "sudo /usr/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other"
  output = ""

[[snippets]]
  description = "python簡易サーバー起動"
  command = "python -m http.server 8000"
  output = ""

[[snippets]]
  description = "youtube-dl 最高画質で保存"
  command = "youtube-dl -f bestvideo+bestaudio --merge-output-format mkv"
  output = ""

[[snippets]]
  description = "youtube-dl mp3で保存"
  command = "youtube-dl -x --audio-format mp3"
  output = ""

[[snippets]]
  description = "youtube-dl mp4で最高画質保存"
  command = "youtube-dl -f mp4/bestvideo+m4a/bestaudio --merge-output-format mp4"
  output = ""

[[snippets]]
  description = "yt-dlp mp3で保存"
  command = "yt-dlp -x --audio-format mp3"
  output = ""

[[snippets]]
  description = "yt-dlp mp4で最高画質保存"
  command = "yt-dlp -f mp4/bestvideo+m4a/bestaudio --merge-output-format mp4"
  output = ""

[[snippets]]
  description = "yt-dlp mp4で最高画質保存(Dドライブ)"
  command = "yt-dlp -o \"/mnt/d/%(title)s.%(ext)s\" -f mp4/bestvideo+m4a/bestaudio --merge-output-format mp4"
  output = ""

[[snippets]]
  description = "youtube-dl チャプターごとに分割してmp3で保存"
  command = "yt-dlp -x --audio-format mp3 --split-chapters"
  output = ""

[[snippets]]
  description = "youtube-dl チャプターごとに分割してmp3で保存(template)"
  command = "yt-dlp -x --audio-format mp3 --split-chapters -o \"chapter:%(section_number)02d %(section_title).100s.%(ext)s\""
  output = ""
